"""add enterprise document metadata

Revision ID: 4535ca6eb9fe
Revises: 1ea38146104c
Create Date: 2026-08-16 15:10:14.447637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4535ca6eb9fe'
down_revision: Union[str, Sequence[str], None] = '1ea38146104c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_title', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_key', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('effective_from', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('effective_to', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('lifecycle_status', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('department', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_document_key'), 'documents', ['document_key'], unique=False)
    op.create_index(op.f('ix_documents_lifecycle_status'), 'documents', ['lifecycle_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_lifecycle_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_key'), table_name='documents')
    op.drop_column('documents', 'department')
    op.drop_column('documents', 'lifecycle_status')
    op.drop_column('documents', 'effective_to')
    op.drop_column('documents', 'effective_from')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'document_key')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'document_title')
    # ### end Alembic commands ###
