"""remove document versioning metadata

Revision ID: cf61a0ac779f
Revises: 4535ca6eb9fe
Create Date: 2026-08-16 16:00:20.088153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf61a0ac779f'
down_revision: Union[str, Sequence[str], None] = '4535ca6eb9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_document_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_lifecycle_status'), table_name='documents')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'effective_from')
    op.drop_column('documents', 'effective_to')
    op.drop_column('documents', 'lifecycle_status')
    op.drop_column('documents', 'document_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('lifecycle_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_documents_lifecycle_status'), 'documents', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_documents_document_key'), 'documents', ['document_key'], unique=False)
    # ### end Alembic commands ###
