"""add document content

Revision ID: fdec5876f889
Revises: 189782ecc74c
Create Date: 2026-08-11 12:16:20.913252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdec5876f889'
down_revision: Union[str, Sequence[str], None] = '189782ecc74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "documents",
        sa.Column(
            "content",
            sa.Text(),
            nullable=True,
        ),
    )

    # Existing documents were created before content was stored.
    # We cannot reconstruct their parsed content from the database.
    # They can remain NULL as legacy records.

    op.alter_column(
        "documents",
        "content",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
